//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait all extends TheoryScala with org.openmath.www.cd.setname1 with org.openmath.www.cd.setname2 with org.openmath.www.cd.logic1 with org.openmath.www.cd.integer1 with org.openmath.www.cd.arith1 with org.openmath.www.cd.arith2 with org.openmath.www.cd.complex1 with org.openmath.www.cd.nums1 with org.openmath.www.cd.list1 with org.openmath.www.cd.list2 with org.openmath.www.cd.set1 with org.openmath.www.cd.set2 with org.openmath.www.cd.fns1 with org.openmath.www.cd.linalg1 with org.openmath.www.cd.linalg2 with org.openmath.www.cd.linalg4 with org.openmath.www.cd.linalg5 with org.openmath.www.cd.relation1 with org.openmath.www.cd.minmax1 with org.openmath.www.cd.rounding1 with org.openmath.www.cd.dimensions1 with org.openmath.www.cd.units_metric1 with org.openmath.www.cd.units_imperial1 with org.openmath.www.cd.units_ops1 with org.openmath.www.cd.units_siprefix1 with org.openmath.www.cd.units_sts with org.openmath.www.cd.units_time with org.openmath.www.cd.units_us1 with org.openmath.www.cd.interval1 with org.openmath.www.cd.polyu with org.openmath.www.cd.poly with org.openmath.www.cd.string with org.openmath.www.cd.transc1 with org.openmath.www.cd.indNat with org.openmath.www.cd.combinat1 with org.openmath.www.cd.permut1 {
}

object all extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "all"

}

