//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait complex1 extends TheoryScala {
  def complex1_complex_cartesian(x1: Term, x2: Term): Term

  def complex1_complex_polar(x1: Term, x2: Term): Term

  def complex1_argument(x1: Term): Term

  def complex1_real(x1: Term): Term

  def complex1_imaginary(x1: Term): Term

  def complex1_conjugate(x1: Term): Term

}

object complex1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "complex1"

  object complex_cartesian extends ConstantScala {
    val parent = _path
    val name = "complex_cartesian"
    def apply(x1: Term, x2: Term) = OMA(OMID(this.path), x1 :: x2:: Nil)
    def unapply(t: Term): Option[(Term, Term)] = t match {
      case OMA(OMID(this.path), x1 :: x2:: Nil) => Some((x1, x2))
      case _ => None
    }
  }


  object complex_polar extends ConstantScala {
    val parent = _path
    val name = "complex_polar"
    def apply(x1: Term, x2: Term) = OMA(OMID(this.path), x1 :: x2:: Nil)
    def unapply(t: Term): Option[(Term, Term)] = t match {
      case OMA(OMID(this.path), x1 :: x2:: Nil) => Some((x1, x2))
      case _ => None
    }
  }


  object argument extends ConstantScala {
    val parent = _path
    val name = "argument"
    def apply(x1: Term) = OMA(OMID(this.path), x1:: Nil)
    def unapply(t: Term): Option[Term] = t match {
      case OMA(OMID(this.path), x1:: Nil) => Some(x1)
      case _ => None
    }
  }


  object real extends ConstantScala {
    val parent = _path
    val name = "real"
    def apply(x1: Term) = OMA(OMID(this.path), x1:: Nil)
    def unapply(t: Term): Option[Term] = t match {
      case OMA(OMID(this.path), x1:: Nil) => Some(x1)
      case _ => None
    }
  }


  object imaginary extends ConstantScala {
    val parent = _path
    val name = "imaginary"
    def apply(x1: Term) = OMA(OMID(this.path), x1:: Nil)
    def unapply(t: Term): Option[Term] = t match {
      case OMA(OMID(this.path), x1:: Nil) => Some(x1)
      case _ => None
    }
  }


  object conjugate extends ConstantScala {
    val parent = _path
    val name = "conjugate"
    def apply(x1: Term) = OMA(OMID(this.path), x1:: Nil)
    def unapply(t: Term): Option[Term] = t match {
      case OMA(OMID(this.path), x1:: Nil) => Some(x1)
      case _ => None
    }
  }


}

