//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait dimensions1 extends TheoryScala {
  def dimensions1_acceleration(): Term

  def dimensions1_area(): Term

  def dimensions1_charge(): Term

  def dimensions1_concentration(): Term

  def dimensions1_current(): Term

  def dimensions1_density(): Term

  def dimensions1_displacement(): Term

  def dimensions1_energy(): Term

  def dimensions1_force(): Term

  def dimensions1_length(): Term

  def dimensions1_mass(): Term

  def dimensions1_momentum(): Term

  def dimensions1_pressure(): Term

  def dimensions1_resistance(): Term

  def dimensions1_speed(): Term

  def dimensions1_temperature(): Term

  def dimensions1_time(): Term

  def dimensions1_velocity(): Term

  def dimensions1_voltage(): Term

  def dimensions1_volume(): Term

}

object dimensions1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "dimensions1"

  object acceleration extends ConstantScala {
    val parent = _path
    val name = "acceleration"
  }


  object area extends ConstantScala {
    val parent = _path
    val name = "area"
  }


  object charge extends ConstantScala {
    val parent = _path
    val name = "charge"
  }


  object concentration extends ConstantScala {
    val parent = _path
    val name = "concentration"
  }


  object current extends ConstantScala {
    val parent = _path
    val name = "current"
  }


  object density extends ConstantScala {
    val parent = _path
    val name = "density"
  }


  object displacement extends ConstantScala {
    val parent = _path
    val name = "displacement"
  }


  object energy extends ConstantScala {
    val parent = _path
    val name = "energy"
  }


  object force extends ConstantScala {
    val parent = _path
    val name = "force"
  }


  object length extends ConstantScala {
    val parent = _path
    val name = "length"
  }


  object mass extends ConstantScala {
    val parent = _path
    val name = "mass"
  }


  object momentum extends ConstantScala {
    val parent = _path
    val name = "momentum"
  }


  object pressure extends ConstantScala {
    val parent = _path
    val name = "pressure"
  }


  object resistance extends ConstantScala {
    val parent = _path
    val name = "resistance"
  }


  object speed extends ConstantScala {
    val parent = _path
    val name = "speed"
  }


  object temperature extends ConstantScala {
    val parent = _path
    val name = "temperature"
  }


  object time extends ConstantScala {
    val parent = _path
    val name = "time"
  }


  object velocity extends ConstantScala {
    val parent = _path
    val name = "velocity"
  }


  object voltage extends ConstantScala {
    val parent = _path
    val name = "voltage"
  }


  object volume extends ConstantScala {
    val parent = _path
    val name = "volume"
  }


}

