//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait linalg2 extends TheoryScala {
  def linalg2_vector(xs1: List[Term]): Term

  def linalg2_matrixrow(xs1: List[Term]): Term

  def linalg2_matrix(xs1: List[Term]): Term

}

object linalg2 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "linalg2"

  object vector extends ConstantScala {
    val parent = _path
    val name = "vector"
    def apply(xs1: List[Term]) = OMA(OMID(this.path), xs1)
    def unapply(t: Term): Option[List[Term]] = t match {
      case OMA(OMID(this.path), xs1) => Some(xs1)
      case _ => None
    }
  }


  object matrixrow extends ConstantScala {
    val parent = _path
    val name = "matrixrow"
    def apply(xs1: List[Term]) = OMA(OMID(this.path), xs1)
    def unapply(t: Term): Option[List[Term]] = t match {
      case OMA(OMID(this.path), xs1) => Some(xs1)
      case _ => None
    }
  }


  object matrix extends ConstantScala {
    val parent = _path
    val name = "matrix"
    def apply(xs1: List[Term]) = OMA(OMID(this.path), xs1)
    def unapply(t: Term): Option[List[Term]] = t match {
      case OMA(OMID(this.path), xs1) => Some(xs1)
      case _ => None
    }
  }


}

