//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api.uom._


object NAMESPACE extends DocumentScala {

    addTheory(org.openmath.www.cd.string)

    addTheory(org.openmath.www.cd.setname1)

    addTheory(org.openmath.www.cd.tensor1)

    addTheory(org.openmath.www.cd.combinat1)

    addTheory(org.openmath.www.cd.arith2)

    addTheory(org.openmath.www.cd.linalg4)

    addTheory(org.openmath.www.cd.nums1)

    addTheory(org.openmath.www.cd.units_imperial1)

    addTheory(org.openmath.www.cd.complex1)

    addTheory(org.openmath.www.cd.linalg1)

    addTheory(org.openmath.www.cd.transc1)

    addTheory(org.openmath.www.cd.dimensions1)

    addTheory(org.openmath.www.cd.units_time)

    addTheory(org.openmath.www.cd.units_metric1)

    addTheory(org.openmath.www.cd.units_siprefix1)

    addTheory(org.openmath.www.cd.fns1)

    addTheory(org.openmath.www.cd.set1)

    addTheory(org.openmath.www.cd.units_ops1)

    addTheory(org.openmath.www.cd.minmax1)

    addTheory(org.openmath.www.cd.polyu)

    addTheory(org.openmath.www.cd.list2)

    addTheory(org.openmath.www.cd.set2)

    addTheory(org.openmath.www.cd.rounding1)

    addTheory(org.openmath.www.cd.all)

    addTheory(org.openmath.www.cd.interval1)

    addTheory(org.openmath.www.cd.linalg2)

    addTheory(org.openmath.www.cd.relation1)

    addTheory(org.openmath.www.cd.setname2)

    addTheory(org.openmath.www.cd.linalg5)

    addTheory(org.openmath.www.cd.list1)

    addTheory(org.openmath.www.cd.integer1)

    addTheory(org.openmath.www.cd.poly)

    addTheory(org.openmath.www.cd.indNat)

    addTheory(org.openmath.www.cd.units_sts)

    addTheory(org.openmath.www.cd.units_us1)

    addTheory(org.openmath.www.cd.arith1)

    addTheory(org.openmath.www.cd.logic1)

    addTheory(org.openmath.www.cd.permut1)

}

