//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_us1 extends TheoryScala {
  def units_us1_acre_us_survey(): Term

  def units_us1_foot_us_survey(): Term

  def units_us1_mile_us_survey(): Term

  def units_us1_pint_us_dry(): Term

  def units_us1_pint_us_liquid(): Term

  def units_us1_yard_us_survey(): Term

}

object units_us1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_us1"

  object acre_us_survey extends ConstantScala {
    val parent = _path
    val name = "acre_us_survey"
  }


  object foot_us_survey extends ConstantScala {
    val parent = _path
    val name = "foot_us_survey"
  }


  object mile_us_survey extends ConstantScala {
    val parent = _path
    val name = "mile_us_survey"
  }


  object pint_us_dry extends ConstantScala {
    val parent = _path
    val name = "pint_us_dry"
  }


  object pint_us_liquid extends ConstantScala {
    val parent = _path
    val name = "pint_us_liquid"
  }


  object yard_us_survey extends ConstantScala {
    val parent = _path
    val name = "yard_us_survey"
  }


}

