//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_metric1 extends TheoryScala {
  def units_metric1_Coulomb(): Term

  def units_metric1_Joule(): Term

  def units_metric1_Newton(): Term

  def units_metric1_Newton_per_sqr_metre(): Term

  def units_metric1_Pascal(): Term

  def units_metric1_Watt(): Term

  def units_metric1_amp(): Term

  def units_metric1_degree_Kelvin(): Term

  def units_metric1_gramme(): Term

  def units_metric1_litre(): Term

  def units_metric1_litre_pre1964(): Term

  def units_metric1_metre(): Term

  def units_metric1_metre_sqrd(): Term

  def units_metric1_metres_per_second(): Term

  def units_metric1_metres_per_second_sqrd(): Term

  def units_metric1_second(): Term

  def units_metric1_volt(): Term

}

object units_metric1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_metric1"

  object Coulomb extends ConstantScala {
    val parent = _path
    val name = "Coulomb"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object Joule extends ConstantScala {
    val parent = _path
    val name = "Joule"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object Newton extends ConstantScala {
    val parent = _path
    val name = "Newton"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object Newton_per_sqr_metre extends ConstantScala {
    val parent = _path
    val name = "Newton_per_sqr_metre"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object Pascal extends ConstantScala {
    val parent = _path
    val name = "Pascal"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object Watt extends ConstantScala {
    val parent = _path
    val name = "Watt"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object amp extends ConstantScala {
    val parent = _path
    val name = "amp"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object degree_Kelvin extends ConstantScala {
    val parent = _path
    val name = "degree_Kelvin"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object gramme extends ConstantScala {
    val parent = _path
    val name = "gramme"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object litre extends ConstantScala {
    val parent = _path
    val name = "litre"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object litre_pre1964 extends ConstantScala {
    val parent = _path
    val name = "litre_pre1964"
  }


  object metre extends ConstantScala {
    val parent = _path
    val name = "metre"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object metre_sqrd extends ConstantScala {
    val parent = _path
    val name = "metre_sqrd"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object metres_per_second extends ConstantScala {
    val parent = _path
    val name = "metres_per_second"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object metres_per_second_sqrd extends ConstantScala {
    val parent = _path
    val name = "metres_per_second_sqrd"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object second extends ConstantScala {
    val parent = _path
    val name = "second"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


  object volt extends ConstantScala {
    val parent = _path
    val name = "volt"
  // no apply method generated for this arity
  // no unapply methods generated for this arity
  }


}

