//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_time extends TheoryScala {
  def units_time_calendar_month(): Term

  def units_time_calendar_year(): Term

  def units_time_day(): Term

  def units_time_hour(): Term

  def units_time_minute(): Term

  def units_time_second(): Term

  def units_time_week(): Term

}

object units_time extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_time"

  object calendar_month extends ConstantScala {
    val parent = _path
    val name = "calendar_month"
  }


  object calendar_year extends ConstantScala {
    val parent = _path
    val name = "calendar_year"
  }


  object day extends ConstantScala {
    val parent = _path
    val name = "day"
  }


  object hour extends ConstantScala {
    val parent = _path
    val name = "hour"
  }


  object minute extends ConstantScala {
    val parent = _path
    val name = "minute"
  }


  object second extends ConstantScala {
    val parent = _path
    val name = "second"
  }


  object week extends ConstantScala {
    val parent = _path
    val name = "week"
  }


}

