//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_siprefix1 extends TheoryScala {
  def units_siprefix1_atto(): Term

  def units_siprefix1_centi(): Term

  def units_siprefix1_deci(): Term

  def units_siprefix1_deka(): Term

  def units_siprefix1_exa(): Term

  def units_siprefix1_femto(): Term

  def units_siprefix1_giga(): Term

  def units_siprefix1_hecto(): Term

  def units_siprefix1_kilo(): Term

  def units_siprefix1_mega(): Term

  def units_siprefix1_micro(): Term

  def units_siprefix1_milli(): Term

  def units_siprefix1_nano(): Term

  def units_siprefix1_peta(): Term

  def units_siprefix1_pico(): Term

  def units_siprefix1_tera(): Term

  def units_siprefix1_yocto(): Term

  def units_siprefix1_yotta(): Term

  def units_siprefix1_zepto(): Term

  def units_siprefix1_zetta(): Term

}

object units_siprefix1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_siprefix1"

  object atto extends ConstantScala {
    val parent = _path
    val name = "atto"
  }


  object centi extends ConstantScala {
    val parent = _path
    val name = "centi"
  }


  object deci extends ConstantScala {
    val parent = _path
    val name = "deci"
  }


  object deka extends ConstantScala {
    val parent = _path
    val name = "deka"
  }


  object exa extends ConstantScala {
    val parent = _path
    val name = "exa"
  }


  object femto extends ConstantScala {
    val parent = _path
    val name = "femto"
  }


  object giga extends ConstantScala {
    val parent = _path
    val name = "giga"
  }


  object hecto extends ConstantScala {
    val parent = _path
    val name = "hecto"
  }


  object kilo extends ConstantScala {
    val parent = _path
    val name = "kilo"
  }


  object mega extends ConstantScala {
    val parent = _path
    val name = "mega"
  }


  object micro extends ConstantScala {
    val parent = _path
    val name = "micro"
  }


  object milli extends ConstantScala {
    val parent = _path
    val name = "milli"
  }


  object nano extends ConstantScala {
    val parent = _path
    val name = "nano"
  }


  object peta extends ConstantScala {
    val parent = _path
    val name = "peta"
  }


  object pico extends ConstantScala {
    val parent = _path
    val name = "pico"
  }


  object tera extends ConstantScala {
    val parent = _path
    val name = "tera"
  }


  object yocto extends ConstantScala {
    val parent = _path
    val name = "yocto"
  }


  object yotta extends ConstantScala {
    val parent = _path
    val name = "yotta"
  }


  object zepto extends ConstantScala {
    val parent = _path
    val name = "zepto"
  }


  object zetta extends ConstantScala {
    val parent = _path
    val name = "zetta"
  }


}

