//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_sts extends TheoryScala {
  def units_sts_unit_prefix(): Term

}

object units_sts extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_sts"

  object unit_prefix extends ConstantScala {
    val parent = _path
    val name = "unit_prefix"
  }


}

