//Source file generated by the Universal OpenMath Machine

package org.openmath.www.cd
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait units_imperial1 extends TheoryScala {
  def units_imperial1_acre(): Term

  def units_imperial1_bar(): Term

  def units_imperial1_foot(): Term

  def units_imperial1_mile(): Term

  def units_imperial1_miles_per_hr(): Term

  def units_imperial1_miles_per_hr_sqrd(): Term

  def units_imperial1_pint(): Term

  def units_imperial1_pound_force(): Term

  def units_imperial1_pound_mass(): Term

  def units_imperial1_yard(): Term

}

object units_imperial1 extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "www.openmath.org") / "cd")
  val _path = _base ? "units_imperial1"

  object acre extends ConstantScala {
    val parent = _path
    val name = "acre"
  }


  object bar extends ConstantScala {
    val parent = _path
    val name = "bar"
  }


  object foot extends ConstantScala {
    val parent = _path
    val name = "foot"
  }


  object mile extends ConstantScala {
    val parent = _path
    val name = "mile"
  }


  object miles_per_hr extends ConstantScala {
    val parent = _path
    val name = "miles_per_hr"
  }


  object miles_per_hr_sqrd extends ConstantScala {
    val parent = _path
    val name = "miles_per_hr_sqrd"
  }


  object pint extends ConstantScala {
    val parent = _path
    val name = "pint"
  }


  object pound_force extends ConstantScala {
    val parent = _path
    val name = "pound_force"
  }


  object pound_mass extends ConstantScala {
    val parent = _path
    val name = "pound_mass"
  }


  object yard extends ConstantScala {
    val parent = _path
    val name = "yard"
  }


}

