//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath
import info.kwarc.mmt.api.uom._


object NAMESPACE extends DocumentScala {

    addDocument(info.kwarc.oaff.openmath.test.NAMESPACE)

    addDocument(info.kwarc.oaff.openmath.uom.NAMESPACE)

}

