//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff
import info.kwarc.mmt.api.uom._


object NAMESPACE extends DocumentScala {

    addDocument(info.kwarc.oaff.openmath.NAMESPACE)

}

