//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import indNat._

trait IndNat extends ViewScala with indNat {
  // UOM start http://oaff.kwarc.info/openmath/uom?IndNat?zero
  def indNat_zero() : Term = {
    OMS(indNat.zero.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?IndNat?zero

  // UOM start http://oaff.kwarc.info/openmath/uom?IndNat?succ
  def indNat_succ(x1: Term) : Term = {
    throw Unimplemented("indNat_succ")
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?IndNat?succ

  declares(Implementation.constant(indNat.zero.path)(indNat_zero _))
  declares(Implementation.A(indNat.succ.path)(indNat_succ _))

}

object IndNat extends IndNat

