//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import linalg4._

trait Linalg4 extends ViewScala with linalg4 {
  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?characteristic_eqn
  def linalg4_characteristic_eqn() : Term = {
    OMS(linalg4.characteristic_eqn.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?characteristic_eqn

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?columncount
  def linalg4_columncount(a: Term) : Term = {
    a match {
      case linalg2.matrix(linalg2.vector(v) :: _) => OMI(v.length)
      case _ => columncount(a)
    }
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?columncount

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?eigenvalue
  def linalg4_eigenvalue() : Term = {
    OMS(linalg4.eigenvalue.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?eigenvalue

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?eigenvector
  def linalg4_eigenvector() : Term = {
    OMS(linalg4.eigenvector.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?eigenvector

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?rank
  def linalg4_rank() : Term = {
    OMS(linalg4.rank.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?rank

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?rowcount
  def linalg4_rowcount(a: Term) : Term = {
    a match {
      case linalg2.matrix(m) => OMI(m.length)
      case _ => rowcount(a) 
    }
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?rowcount

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg4?size
  def linalg4_size(a: Term) : Term = {
    a match {
      case linalg2.vector(v) => OMI(v.length)
      case _ => size(a)
    }
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg4?size

  declares(Implementation.constant(linalg4.characteristic_eqn.path)(linalg4_characteristic_eqn _))
  declares(Implementation.A(linalg4.columncount.path)(linalg4_columncount _))
  declares(Implementation.constant(linalg4.eigenvalue.path)(linalg4_eigenvalue _))
  declares(Implementation.constant(linalg4.eigenvector.path)(linalg4_eigenvector _))
  declares(Implementation.constant(linalg4.rank.path)(linalg4_rank _))
  declares(Implementation.A(linalg4.rowcount.path)(linalg4_rowcount _))
  declares(Implementation.A(linalg4.size.path)(linalg4_size _))

}

object Linalg4 extends Linalg4

