//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import linalg2._

trait Linalg2 extends ViewScala with linalg2 {
  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg2?vector
  def linalg2_vector(ls: List[Term]) : Term = {
    vector(ls)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg2?vector

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg2?matrixrow
  def linalg2_matrixrow(ls: List[Term]) : Term = {
    vector(ls)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg2?matrixrow

  // UOM start http://oaff.kwarc.info/openmath/uom?Linalg2?matrix
  def linalg2_matrix(ls: List[Term]) : Term = {
    if (ls.length == 1) ls(0) else matrix(ls)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Linalg2?matrix

  declares(Implementation.S(linalg2.vector.path)(linalg2_vector _))
  declares(Implementation.S(linalg2.matrixrow.path)(linalg2_matrixrow _))
  declares(Implementation.S(linalg2.matrix.path)(linalg2_matrix _))

}

object Linalg2 extends Linalg2

