//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import list1._

trait List1 extends ViewScala with list1 {
  // UOM start http://oaff.kwarc.info/openmath/uom?List1?list
  def list1_list(ls: List[Term]) : Term = {
    list(ls)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?List1?list

  // UOM start http://oaff.kwarc.info/openmath/uom?List1?map
  def list1_map(f: Term, c: Term) : Term = {
    c match {
      case list(ls) => list(ls.map(t => OMA(f, List(t))))
      case set1.set(s) => set1.set(s.map(t => OMA(f, List(t))))
      case interval1.integer_interval(a, b) => interval1.integer_interval(OMA(f, List(a)), OMA(f, List(b)))
    }
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?List1?map

  // UOM start http://oaff.kwarc.info/openmath/uom?List1?suchthat
  def list1_suchthat() : Term = {
    OMS(list1.suchthat.path)
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?List1?suchthat

  declares(Implementation.S(list1.list.path)(list1_list _))
  declares(Implementation.AA(list1.map.path)(list1_map _))
  declares(Implementation.constant(list1.suchthat.path)(list1_suchthat _))

}

object List1 extends List1

