//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import string._

trait OMString extends ViewScala with string {
  // UOM start http://oaff.kwarc.info/openmath/uom?String?strlen
  def string_strlen(x1: Term) : Term = {
    throw Unimplemented("string_strlen")
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?String?strlen

  // UOM start http://oaff.kwarc.info/openmath/uom?String?strcat
  def string_strcat(x1: Term, x2: Term) : Term = {
    throw Unimplemented("string_strcat")
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?String?strcat

  // UOM start http://oaff.kwarc.info/openmath/uom?String?substr
  def string_substr(x1: Term, x2: Term) : Term = {
    throw Unimplemented("string_substr")
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?String?substr

  declares(Implementation.A(string.strlen.path)(string_strlen _))
  declares(Implementation.AA(string.strcat.path)(string_strcat _))
  declares(Implementation.AA(string.substr.path)(string_substr _))

}

object OMString extends OMString

