//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.uom
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import org.openmath.www.cd._

import tensor1._

trait Tensor1 extends ViewScala with tensor1 {
  // UOM start http://oaff.kwarc.info/openmath/uom?Tensor1?tuple
  def tensor1_tuple(xs1: List[Term]) : Term = {
    throw Unimplemented("tensor1_tuple")
  }
  // UOM end http://oaff.kwarc.info/openmath/uom?Tensor1?tuple

  declares(Implementation.S(tensor1.tuple.path)(tensor1_tuple _))

}

object Tensor1 extends Tensor1

