//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import info.kwarc.oaff.openmath.test._

import Arith._

trait ArithTest extends ViewScala with Arith with info.kwarc.oaff.openmath.uom.Arith1 with info.kwarc.oaff.openmath.uom.Nums1 with info.kwarc.oaff.openmath.uom.Relation1 with info.kwarc.oaff.openmath.uom.Logic1 {

}

object ArithTest extends ArithTest

