//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait Integer extends TheoryScala with org.openmath.www.cd.integer1 with org.openmath.www.cd.nums1 with org.openmath.www.cd.relation1 with org.openmath.www.cd.logic1 {
  val Integer_factorialTest = _assert("Integer_factorialTest", _ => relation1_eq(integer1_factorial(OMI(4)), OMI(24)), _ == logic1_true())

  val Integer_factorofTest = _assert("Integer_factorofTest", _ => integer1_factorof(OMI(3), relation1_eq(OMI(6), logic1_true)), _ == logic1_true())

  val Integer_quotientTest = _assert("Integer_quotientTest", _ => integer1_quotient(OMI(6), relation1_eq(OMI(3), OMI(2))), _ == logic1_true())

  val Integer_remainderTest = _assert("Integer_remainderTest", _ => integer1_remainder(OMI(7), relation1_eq(OMI(3), OMI(1))), _ == logic1_true())

}

object Integer extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "oaff.kwarc.info") / "openmath" / "test")
  val _path = _base ? "Integer"

  object factorialTest extends ConstantScala {
    val parent = _path
    val name = "factorialTest"
  }


  object factorofTest extends ConstantScala {
    val parent = _path
    val name = "factorofTest"
  }


  object quotientTest extends ConstantScala {
    val parent = _path
    val name = "quotientTest"
  }


  object remainderTest extends ConstantScala {
    val parent = _path
    val name = "remainderTest"
  }


}

