//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import info.kwarc.oaff.openmath.test._

import Linalg._

trait LinalgTest extends ViewScala with Linalg with info.kwarc.oaff.openmath.uom.Arith1 with info.kwarc.oaff.openmath.uom.Relation1 with info.kwarc.oaff.openmath.uom.Logic1 with info.kwarc.oaff.openmath.uom.Linalg1 with info.kwarc.oaff.openmath.uom.Linalg2 with info.kwarc.oaff.openmath.uom.Linalg4 {

}

object LinalgTest extends LinalgTest

