//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import info.kwarc.oaff.openmath.test._

import Logic._

trait LogicTest extends ViewScala with Logic with info.kwarc.oaff.openmath.uom.Relation1 with info.kwarc.oaff.openmath.uom.Logic1 {

}

object LogicTest extends LogicTest

