//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

trait Minmax extends TheoryScala with org.openmath.www.cd.relation1 with org.openmath.www.cd.logic1 with org.openmath.www.cd.minmax1 with org.openmath.www.cd.list1 {
  val Minmax_minTest = _assert("Minmax_minTest", _ => minmax1_min(relation1_eq(list1_list(List(OMI(3), OMI(1), OMI(2), OMI(4))), OMI(1))), _ == logic1_true())

  val Minmax_maxTest = _assert("Minmax_maxTest", _ => minmax1_max(relation1_eq(list1_list(List(OMI(3), OMI(1), OMI(2), OMI(4), OMI(3))), OMI(4))), _ == logic1_true())

}

object Minmax extends TheoryScalaAux {
  val _base = DPath(utils.URI("http", "oaff.kwarc.info") / "openmath" / "test")
  val _path = _base ? "Minmax"

  object minTest extends ConstantScala {
    val parent = _path
    val name = "minTest"
  }


  object maxTest extends ConstantScala {
    val parent = _path
    val name = "maxTest"
  }


}

