//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api.uom._


object NAMESPACE extends DocumentScala {

    addTheory(info.kwarc.oaff.openmath.test.Integer)

    addTheory(info.kwarc.oaff.openmath.test.Relation)

    addView(info.kwarc.oaff.openmath.test.MinmaxTest)

    addTheory(info.kwarc.oaff.openmath.test.Complex)

    addView(info.kwarc.oaff.openmath.test.RelationTest)

    addView(info.kwarc.oaff.openmath.test.RoundingTest)

    addView(info.kwarc.oaff.openmath.test.IntegerTest)

    addView(info.kwarc.oaff.openmath.test.ArithTest)

    addTheory(info.kwarc.oaff.openmath.test.Rounding)

    addView(info.kwarc.oaff.openmath.test.SetTest)

    addTheory(info.kwarc.oaff.openmath.test.Logic)

    addTheory(info.kwarc.oaff.openmath.test.OMSet)

    addView(info.kwarc.oaff.openmath.test.ComplexTest)

    addTheory(info.kwarc.oaff.openmath.test.Linalg)

    addView(info.kwarc.oaff.openmath.test.LogicTest)

    addTheory(info.kwarc.oaff.openmath.test.Arith)

    addView(info.kwarc.oaff.openmath.test.LinalgTest)

    addTheory(info.kwarc.oaff.openmath.test.Minmax)

    addView(info.kwarc.oaff.openmath.test.ListTest)

    addTheory(info.kwarc.oaff.openmath.test.OMList)

}

