//Source file generated by the Universal OpenMath Machine

package info.kwarc.oaff.openmath.test
import info.kwarc.mmt.api._
import objects._
import uom._
import ConstantScala._

import info.kwarc.oaff.openmath.test._

import Rounding._

trait RoundingTest extends ViewScala with Rounding with info.kwarc.oaff.openmath.uom.Relation1 with info.kwarc.oaff.openmath.uom.Logic1 with info.kwarc.oaff.openmath.uom.Rounding1 {

}

object RoundingTest extends RoundingTest

