//Source file generated by the Universal OpenMath Machine

package org.openmath.www
import info.kwarc.mmt.api.uom._


object NAMESPACE extends DocumentScala {

    addDocument(org.openmath.www.cd.NAMESPACE)

}

